[tool.poetry]
name = "cloudmanufacturing"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "cloudmanufacturing" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
tqdm = "^4.66.1"
numpy = "^1.26.1"
pandas = "^2.1.2"
mip = "^1.15.0"
torch = "^2.1.0"
dgl = "1.1.2"
dvc = "^3.28.0"
pre-commit = "^3.5.0"
ruamel-yaml = "^0.18.5"
matplotlib = "^3.8.1"
scikit-learn = "^1.3.2"
openpyxl = "^3.1.2"
dvc-gdrive = "^2.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
